<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UserSecretsId>d0da115b-8ad0-41e8-8d79-16d1d40798bb</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotNetCoreWebApi.Logic\DotNetCoreWebApi.Logic.csproj" />
    <ProjectReference Include="..\DotNetCoreWebApi.Metrics\DotNetCoreWebApi.Metrics.csproj" />
    <ProjectReference Include="..\DotNetCoreWebApi.Providers\DotNetCoreWebApi.Providers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
