#!/usr/bin/python3

"""
  This sample code demonstrates how to use Intrado's Emergency Data Broker API.
  It shows how to initiate a search and how to retrieve a stream of results.
  In addition, it shows how to terminate an event and how to generate the 
  necessary JWT.

  The call to 'initiate-search' is needed in any case. It returns a Short
  Web Link (SWL), for example https://d91.io/abc123. This web link can be used to
  display the search results and updates that may happen to the events found.

  The terminate call will stop the updates. Even though not mandatory, it is
  recommended to call terminate at some point after each query.

  A call to 'retrieve-swl-data' can be used to retrieve the results as a JSON
  stream. This call requires the path of the short web link returned by
  'initiate-search', in this example abc123, as a parameter.

  Some search types provide additional data that can be retrieved in a second
  step by performing an 'additional-data-search'.

  2022-01-28
""" 

import time
import sys
import jwt
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend
import requests
import json
import re
from threading import Thread
import getopt


#------------------------------------------------------------------------------------------------------

#----- Global Configuration Variables -----

verbose = False        # can be changed via command line parameter
printResults = False   # can be changed via command line parameter
waitTime = 15          # seconds, can be changed via command line parameter

# Settings provided by Intrado
baseUrl = 'https://broker.sqa.powerdata.west.com'
orgId = '4440004000'

"""
  You will need a private key to sign your JWTs. The key length can be either 1024, 2048 or 4096 bit.

  A password protected private key with a length of 2048 bit can be generated like this:
    openssl genrsa -aes256 -passout file:passphrase.txt -out key.private.pem 2048

  A private key without a password can be generated like this:
    openssl genrsa -out key.private.pem 2048

  The public key can be extracted with the following command:
    openssl rsa -in key.private.pem -passin file:passphrase.txt -outform PEM -pubout -out key.public.pem
  Intrado will have to load your public into the EDB configuration.

  During testing, we'll use keys generated by Intrado, but in production you should create your
  own key pair.
"""

# Key for signing the JWTs
keystore_PrivateKeyFile = 'key2048_sqa.private.pem'
keystore_PassPhraseFile = 'passphrase.txt'


#------------------------------------------------------------------------------------------------------

def usage():

  print ('Usage: ' + sys.argv[0] + '\n',
         '       -h | --help            show this help and exit\n',
         '       -v | --verbose         display details about the query progress\n',
         '       -p | --print           print results on the console (results are always logged in a file)\n',
         '       -w | --wait     [n]    wait for n seconds until a terminate is sent, default: 15s\n',
         '       -q | --query    [id]   use predefied query sample')


#------------------------------------------------------------------------------------------------------

def createJWT():

  # Load the private key
  try:
    private_key = open(keystore_PrivateKeyFile).read().encode()

    # if the private key is password protected:
    passphrase = open(keystore_PassPhraseFile).read().rstrip('\n').encode()
    # otherwise:
    #passphrase = None

    key = serialization.load_pem_private_key(
      private_key, password=passphrase, backend=default_backend()
    )
  except:
    print('Unable to extract private key from keystore', file=sys.stderr)
    return None

  # Get the current time as a Unix time stamp
  now = int(time.time())

  # Set the mandatory claims for the JWT
  claims = dict()
  claims['iss'] = orgId                     # the issuer must be something unique
  claims['iat'] = now                       # issued at the current time
  claims['exp'] = now + 3600 * 24 * 30      # expiry in one hour, you could use other values
  claims['authorities'] = ['ROLE_SEARCH']   # mandatory for EDB
  claims['orgId'] = orgId                   # mandatory for EDB
  claims['user_name'] = 'testscript'        # should reflect the actual user making the query

  # Generate the JWT
  encoded_jwt = jwt.encode(claims, key, algorithm='RS256')
  return encoded_jwt.decode('ascii')


#------------------------------------------------------------------------------------------------------

def initiateSearch (jwt, query, incidentId):

  """
    Initiate a search to retrieve information relevant to a location,
    telephone number, civic address and an optional list of search types.
    This search is done asynchronously and this call returns immediately
    with a SWL which can be used to view the search results.

    Path:    https://[BrokerBaseUrl]/v1/initiate-search
    Method:  POST
    Body:    see below for details

    Headers:

      Header Name    | Required | Header Value
      ---------------+----------+----------------------------------------------
      Authorization  | Yes      | JWT
      IncidentId     | Yes      | Unique Id for call
      StationUser    | No       | Caller username
      StationId      | No       | Caller station
      Content-Type   | Yes      | “application/json”
      TransactionId  | No       | Optional ID to track API call in server log


    Searches accept query bodies as follows:

      { “location”: {
          "datum": <geodetic datum>,
          “latitude”: <decimal degrees from equator>,
          “longitude": <decimal degrees from prime meridian>,
          "altitude": <meters above sea level>,
          "uncertainty": <percentage>,
          "confidence": {
            "value": <string>,
            "pdf": <string>
          }
        },
        “phone”: <10 digit phone#>,
        "address": {
          "A1": <state, two-characters>,
          "A2": <county>,
          "A3": <city>,
          "RD": <street>,
          "STS": <street suffix>,
          "POD": <trailing street suffix>,
          "HNO": <house number>,
          "LOC": <location>,
          "PC": <postal code>
        }
        "searchTypes": [list of search types]
      }

      All values in this structure are optional in the sense that the API does not enforce
      their presence. However, each search type requires certain fields in order to work.
      The address structure can contain any of the PDIF-LO fields.

      The list of Search Types can change. The current list of search types includes the
      following:
        - Safety Shield       (requires location)
        - Alarm               (requires phone, location is optional)
        - Commercial Phone    (requires phone)
        - Commercial Locate   (requires location and phone)
        - Commercial Address  (requires address)
        - Telematics sim      (requires location)
  """

  url = baseUrl + '/v1/initiate-search'

  headers = {
    'Authorization': "Bearer " + jwt,
    'IncidentId': incidentId,
    'Content-Type': 'application/json'
  }

  if verbose:
    print("----- initiateSearch request -----")
    print("url:", url)
    print("headers:", headers)
    print("data:", query)

  r = requests.post(url, data=json.dumps(query), headers=headers)

  if verbose:
    print("----- initiateSearch response -----")
    print("status code:", r.status_code)
    print("headers:", r.headers)
    print("body:", r.text)

  if r.status_code == 200:
    # Extract Security Word from previous result
    m = re.search("^http.*/(\w\w\w\d\d|\d\d\w\w\w)$", r.text)
    if m:
      if verbose:
        print("Security Word:", m[1])
      return m[1]
    else:
      print("cannot extract Security Word", file=sys.stderr)
      return None

  else:
    print("InitiateSearch failed", file=sys.stderr)
    return None
  

#------------------------------------------------------------------------------------------------------

def retrieveData (jwt, securityWord, fileName, additionalData):

  """
    Retrieve search results for a Short Web Link for an authenticated user.

    Path:    https://[BrokerBaseUrl]/v1/retrieve-swl-data
    Method:  GET
    Body:    none

    Query Parameters:
      SecurityWord:  Security Word corresponding to the SWL. The Security Word is
                     a unique (at any given time) identifier for the search results
                     for a given call or incident, and is the last component of the SWL.

    Headers:

      Header Name    | Required | Header Value
      ---------------+----------+----------------------------------------------
      Authorization  | Yes      | JWT
      Accept         | No       | text/event-stream
      TransactionId  | No       | Optional ID to track API call in server log
  """

  url = baseUrl + '/v1/retrieve-swl-data'

  headers = {
    'Authorization': "Bearer " + jwt,
    'Accept': 'text/event-stream'
  }

  parameters = {
    'SecurityWord': securityWord
  }

  r = requests.get(url, params=parameters, headers=headers, stream=True)

  if verbose:
    print("----- retrieveData response -----")
    print("status code:", r.status_code)
    print("headers:", r.headers)
    print("writing to file", fileName)

  #----- Process the result -----
  threadCounter = 0
  for line in r.iter_lines():
    line = line.decode()
    if printResults:
      print("line", line)

    if line[:4] == 'data' and line[5:] != '{}':
      # Parse result as JSON
      jline = json.loads(line[5:])
      # Print result to file
      f = open(fileName, "a")
      f.write(json.dumps(jline, indent=2) + "\n")
      f.close()

      # If needed, launch 'additional-data-search' in separate threads.
      # The additional data streams do not close when 'terminate' is called.
      # The threads are started with daemon=True so they get terminated when
      # this program finishes.
 
      if additionalData:
        try:
          uniqueSearchId = jline['data']['uniqueSearchId']
          searchResult = jline['data']['searchResult']

          # 'searchResult' contains either a JSON document with a single result
          # or an element 'results' containing an array. If we have the latter,
          # we need to perform multiple searches.

          sequence = [-1]  # default in case we don't have an array

          if 'results' in searchResult:
            results = searchResult['results']
            # Check whether we reveived an array
            if type(results).__name__ == 'list':
              # Array: call retrieveAdditionalData for each element
              sequence = range(0, len(results))

          for i in sequence:
            threadCounter = threadCounter + 1
            threadId = str(threadCounter).zfill(4)
            t = Thread(target=retrieveAdditionalData, args=(jwt, uniqueSearchId, i, fileName, threadId), daemon=True)
            t.start()
        except:
          pass

#------------------------------------------------------------------------------------------------------

def retrieveAdditionalData (jwt, uniqueSearchId, index, fileName, threadId):

  """
    Search for additional data related to a previous search. Providers
    may be configured to provide additional streamed data related to a
    previous search. If so, this call will return that data stream. If the
    incident is in-progress, then the stream will stay active until the
    incident is CLOSED (since more searches may be made for the
    incident). Note that a SSE event value of "PING" is sent periodically
    with an empty data element to prevent socket timeouts for long
    running streams.

    Path:    https://[BrokerBaseUrl]/v1/additional-data-search
    Method:  GET
    Body:    none

    Query Parameters:
      SearchId:     This the value corresponding to the "uniqueSearchId"
                    name in a (prior) search result payload JSON response.
      ResultIndex:  Required for providers that return an array of
                    results corresponding to a search ID, this
                    index specifies which result to return
                    additional data for.

    Headers:

      Header Name    | Required | Header Value
      ---------------+----------+----------------------------------------------
      Authorization  | Yes      | JWT
      Accept         | No       | text/event-stream
      TransactionId  | No       | Optional ID to track API call in server log
  """

  url = baseUrl + '/v1/additional-data-search'

  headers = {
    'Authorization': "Bearer " + jwt,
    'Accept': 'text/event-stream'
  }

  parameters = {
    'SearchId': uniqueSearchId
  }
  if index >= 0:
    parameters['ResultIndex'] = index

  fn = fileName + '_' + threadId

  r = requests.get(url, params=parameters, headers=headers, stream=True)

  if verbose:
    print(threadId, "result index:", index)
    print(threadId, "status code:", r.status_code)
    print(threadId, "headers:", r.headers)
    print(threadId, "writing to file", fn)

  #----- Process the result -----
  for line in r.iter_lines():
    line = line.decode()
    if printResults:
      print(threadId, "line", line)

    if line[:4] == 'data' and line[5:] != '{}':
      # Parse result as JSON
      jline = json.loads(line[5:])
      # Print result to file
      f = open(fn, "a")
      f.write(json.dumps(jline, indent=2) + "\n")
      f.close()


#------------------------------------------------------------------------------------------------------

def terminateCall (jwt, incidentId):

  """
    Notifies EDB that a call has terminated and no more searches related to
    this incident will be requested. This will terminate streaming of all EDB
    search results related to the incident.

    Path:    https://[BrokerBaseUrl]/v1/terminate/[incidentId]
    Method:  DELETE
    Body:    none

    Headers:

      Header Name    | Required | Header Value
      ---------------+----------+----------------------------------------------
      Authorization  | Yes      | JWT
      StationUser    | No       | Caller username
      StationId      | No       | Caller station
      TransactionId  | No       | Optional ID to track API call in server log
  """

  url = baseUrl + '/v1/terminate/' + incidentId

  headers = {
    'Authorization': "Bearer " + jwt
  }

  r = requests.delete(url, headers=headers)

  if verbose:
    print("----- terminateCall response -----")
    print("status code:", r.status_code)


#------------------------------------------------------------------------------------------------------

def waitAndTerminate(seconds, jwt, incidentId):

  # Sleep for some time, then call "terminate"
  time.sleep(seconds)
  if verbose:
    print("terminating")
  terminateCall (jwt, incidentId)


#======================================================================================================

#----- Check command line options -----
try:
  opts, args = getopt.getopt(sys.argv[1:], "hvpq:w:", ["help", "verbose", "print", "query=", "wait="])
except getopt.GetoptError:
  usage()
  sys.exit(1)

if opts:
  for opt, arg in opts:
    if opt in ('-h', '--help'):
      usage()
      sys.exit(0)
    elif opt in ('-w', '--wait'):
      try:
        waitTime = int(arg)
      except:
        usage()
        sys.exit(1)
    elif opt in ('-v', '--verbose'):
      verbose = True
    elif opt in ('-p', '--print'):
      printResults = True
    elif opt in ('-q', '--query'):
      query = arg
else:
  usage()
  sys.exit(1)

if not 'query' in locals():
  usage()
  sys.exit(1)


#----- Sample queries -----

if query == '1':
  # Example 1: Query events from alarm companies
  queryDoc = {
    "phone": "3034448899",
    "searchTypes": ["Alarm"]
  }
  additionalData = True

elif query == '2':
  # Example 2: Query phone numbers in commercial databases
  # WARNING: The data is real, do not query arbitrary phone numbers.
  #          Please use the number provided here or your own phone number.
  #          This search takes time, if you set the wait time too
  #          short, you will not get any results.
  queryDoc = {
    "phone": "7203793562",
    "searchTypes": ["Commercial Phone"]
  }
  additionalData = False

elif query == '3':
  # Example 3: Query phone numbers and locations in commercial databases
  # WARNING: The data is real, do not query arbitrary phone numbers and locations.
  #          Please use the data provided here or your own data.
  #          This search takes time, if you set the wait time too
  #          short, you will not get any results.
  queryDoc = {
    "phone": "7203793562",
    "location": {
      "latitude": 39.376129,
      "longitude": -76.603939
    },
    "searchTypes": ["Commercial Locate"]
  }
  additionalData = False

elif query == '4':
  # Example 4: Query address in commercial databases
  # WARNING: The data is real, do not query arbitrary phone numbers and locations.
  #          Please use the data provided here or your own data.
  #          This search takes time, if you set the wait time too
  #          short, you will not get any results.
  queryDoc = {
    "address": {
      "A1":  "CO",
      "A3":  "ERIE",
      "RD":  "DELLA",
      "STS": "CT",
      "HNO": "1616",
      "PC":  "80516"
    },
    "searchTypes": ["Commercial Address"]
  }
  additionalData = False

elif query == '5':
  # Example 5: Query Intrado's Safety Shield application
  queryDoc = {
    "location": {
      "latitude": 39.0492,
      "longitude": -95.68561
    },
    "phone": "7203793562",
    "searchTypes": ["Safety Shield"]
  }
  additionalData = False

elif query == '6':
  # Example 6: Query simulated telematics data
  queryDoc = {
    "location": {
      "latitude": 39.0492,
      "longitude": -95.68561
    },
    "searchTypes": ["Telematics sim"]
  }
  additionalData = False

else:
  print("No query has been defined for this parameter.")
  sys.exit(1)


#----- Carry out searches -----

# Create a JSON Web Token (JWT) for authentication
jwt = createJWT()

if not jwt:
  sys.exit(1)

if verbose:
  print("----- JWT -----")
  print ('JWT: ' + jwt, file=sys.stderr)

# Generate a unique incident ID. Here we're using a Unix timestamp. A UUID or an ID from the
# client application would be other possibilities.
incidentId = str(int(time.time()))

# Initate the search
securityWord = initiateSearch (jwt, queryDoc, incidentId)
if not securityWord:
  sys.exit(1)

# Start a thread that will terminate the search after a certain time
t = Thread(target=waitAndTerminate, args=(waitTime, jwt, incidentId))
t.start()

# Retrieve the data. This will open a stream that will continue until the 'terminate' call.
# This step is optional. The SWL returned by 'iniateSearch' can also be used to render the results.
fileName = 'results_' + incidentId
retrieveData (jwt, securityWord, fileName, additionalData)


